### ISSUE TITLE
Slug / ID for speaker

### ISSUE THREAD

**Issue by envycontent** [ox-it/talks.ox#245]
Here, you give the id for the speaker but not the slug - whereas for the talk itself I see the slug not the id - this might be intentional - just thought I had better check.

https://talks-dev.oucs.ox.ac.uk/api/events/search?from=01/01/01&speaker=f8ecded3-d2af-4585-bd3b-5cd7440795b9

**Comment by ahaith** [comment]
Not intentional - IMO we should probably provide both in the API.
N.B. the current API on talks-dev isn't the latest version. We've got a branch #211 in which we're working on a HAL version, which will provide a more standard structure and I think it may also include some changes to what information is returned. We'll need to update the documentation for it too.
We should hopefully be in a position to deploy that to staging sometime tomorrow.

**Comment by envycontent** [comment]
Great, thanks, I'll stand by

**Comment by ahaith** [comment]
Sorry I misread your original note - ignore my last comment at providing both. We should only provide the slug, and I think the new branch is already configured that way.
