### ISSUE TITLE
Finding people

### ISSUE THREAD

**Issue by envycontent** [ox-it/talks.ox#260]
At present its a bit tricky to find people on the dashboard. E.g. for Fiona Woods I had to click on next about 17 times. Probably would be good to configure the search as well for people. Not hugely urgent.

**Comment by ahaith** [comment]
On the dashboard pages, we could also allow jumping to a specific letter of the alphabet, or jump to a specific page, rather than just hitting 'next' multiple times.

It would be quite easy to have the text search cover the names of speakers/organisers/hosts, and so return every talk they are involved with. However, providing a link to that person from the results page is a little more of a challenge.

**Comment by envycontent** [comment]
A specific letter A-Z would be good, this is how it works on the old
Oxford Talks and I'm finding it useful. However, can we order
alphabetically by surname? I should imagine it is possible to prise out
the surname from the name unless someone has letters after their name
(as they are wont to do for academics).

I think it would be good for the search to cover at least speakers,
hosts and organisers would also be useful. Probably not necessary to
link the search result to their page, the talks listing is sufficient.
However, while the A-Z listing on the dashboard is fairly important
right now (as it is a bit of a struggle to locate someone), the search
is less important and could be left for the next phase.

Anne

**Comment by ahaith** [comment]
The Person dashboard does attempt to order alphabetically by surname. It largely gets it right, but there are a few stragglers who appear at the start for some reason. I'll see if I can find out why.

Re: Person search. In fact we already do return hits on speaker names, so that could be a quicker way to navigate to the page for a specific Person (search name, browse to talk they speak at, click name)

**Comment by ahaith** [comment]
OK, some people have a trailing space in their name, which puts them first in the 'alphabetical-by-surname' list. I'll address that now.

**Comment by ahaith** [comment]
Since we don't store surname in its own right, it would actually be far simpler to filter on first character of the name overall. Does that sound OK?

**Comment by envycontent** [comment]
I can see one problem in that we're likely to get lots of Prof. and Dr
in there which will be a bit meaningless. However, if we really can find
anyone via search (I'll experiment) then we can document how to get to
someone via that direction and take the simpler first character approach
for the Dashboard.

**Comment by ahaith** [comment]
I had a bit of time left over this afternoon so have implemented the filter on surname. Will leave deployment until Monday however.
